server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active:
    - git
    #- native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/UMounika321/zetta-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations:
#          - "file:///zettamine/config"
          #- "classpath:/config"
encrypt:
  key: "mounika@zettabank.com"
